# ChittyConnect Configuration for chittycore
service:
  name: chittycore
  display_name: Chittycore
  type: library
  tier: 2
  organization: CHITTYOS
  chitty_id: ${CHITTYCORE_SERVICE_ID}
  domains:
    production: core.chitty.cc

onboarding:
  endpoint: https://get.chitty.cc/api/onboard
  provisions: [chitty_id, service_token, certificate, trust_chain]

auth:
  provider: chittyauth
  endpoint: https://auth.chitty.cc
  service_token:
    source: chittyconnect
    key: CHITTYCORE_SERVICE_TOKEN

secrets:
  provider: chittyconnect
  vault: 1password
  paths:
    production: op://ChittyOS/chittycore-prod

github:
  repository: CHITTYOS/chittycore

monitoring:
  health:
    endpoint: /health
    interval: 60s
